[package]
name = "voxa-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
wasmtime = { version = "36.0.2", optional = true }
wasmtime-wasi = { version = "36.0.2", features = ["preview1"], optional = true }

[features]
default = ["loader"]
loader = ["wasmtime", "wasmtime-wasi"]
